#:import utils kivy.utils

<AppWindow>:
    BoxLayout:
        Label:
            id:window
            bcolor: '#1a191b'
            canvas.before:
                Color:
                    rgb: utils.get_color_from_hex(self.bcolor)
                Rectangle:
                    pos: self.pos
                    size: self.size
            GridLayout:
                pos:window.pos
                size:window.size
                rows:2

                GridLayout:
                    cols:2

                    GridLayout:
                        rows:2
                        TextInput:
                            id:length_input
                            text:"Enter length of sequence"
                            multiline:False

                        Label:
                            text:"Blrh"

                    Button:
                        id:generate_button
                        seq:'Generate'
                        text:self.seq
                        background_normal:''
                        background_color:utils.get_color_from_hex("#1e1d1f")
                        on_press:
                            self.background_color=utils.get_color_from_hex("#111111")
                        on_press:
                            self.seq:root.btn_clk_generate(length_input.text)
                        on_release:
                            self.background_color=utils.get_color_from_hex("#1e1d1f")

                Label:
                    text:root.output
                    text_size:self.size
                    valign:'middle'
